# Generated by Django 4.2.7 on 2023-12-13 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fakultety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='gruppy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shifr', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kafedry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('zav_name', models.CharField(max_length=100)),
                ('zav_secname', models.CharField(max_length=100)),
                ('zav_surename', models.CharField(max_length=100, null=True)),
                ('fakultet_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fakultety')),
            ],
        ),
        migrations.CreateModel(
            name='NIRs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('date_start', models.DateTimeField(null=True)),
                ('type', models.CharField(choices=[('kf', 'konferensia'), ('vs', 'vistavka'), ('ol', 'olimpiada')], max_length=3)),
                ('Fakultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fakultety')),
            ],
        ),
        migrations.CreateModel(
            name='studenty',
            fields=[
                ('num_zachetka', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('secname', models.CharField(max_length=100)),
                ('surename', models.CharField(max_length=100, null=True)),
                ('gruppa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.gruppy')),
            ],
        ),
        migrations.CreateModel(
            name='uchastnikyOnNIR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idParticipent', models.BooleanField(default=False)),
                ('nir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nirs')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.studenty')),
            ],
        ),
        migrations.CreateModel(
            name='spetsialnosti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('kafedra_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kafedry')),
            ],
        ),
        migrations.CreateModel(
            name='sotrudnikyiOnKafedra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(choices=[('as', 'asperan'), ('te', 'teacher')], max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('secname', models.CharField(max_length=100)),
                ('surename', models.CharField(max_length=100, null=True)),
                ('degree', models.CharField(choices=[('bk', 'bakalavr'), ('kn', 'kandidat nauk'), ('dn', 'doktor nauk'), ('mg', 'magistr')], max_length=3)),
                ('kafedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kafedry')),
            ],
        ),
        migrations.CreateModel(
            name='orgkomitety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAgent', models.BooleanField(default=False)),
                ('isParticipent', models.BooleanField(default=False)),
                ('nir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nirs')),
                ('sotrudnikiOnKafedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sotrudnikyionkafedra')),
            ],
        ),
        migrations.AddField(
            model_name='gruppy',
            name='spetsialnost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.spetsialnosti'),
        ),
    ]
