# Generated by Django 4.2.7 on 2023-12-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NIRs',
            new_name='NIR',
        ),
        migrations.AlterField(
            model_name='sotrudnikyionkafedra',
            name='degree',
            field=models.CharField(choices=[('mg', 'magistr'), ('kn', 'kandidat nauk'), ('bk', 'bakalavr'), ('dn', 'doktor nauk')], max_length=3),
        ),
        migrations.AlterField(
            model_name='sotrudnikyionkafedra',
            name='job',
            field=models.CharField(choices=[('te', 'teacher'), ('as', 'asperan')], max_length=3),
        ),
    ]
