# Generated by Django 4.2.7 on 2023-12-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_nirs_nir_alter_sotrudnikyionkafedra_degree_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uchastnikyonnir',
            old_name='idParticipent',
            new_name='isParticipent',
        ),
        migrations.AlterField(
            model_name='nir',
            name='type',
            field=models.CharField(choices=[('ol', 'olimpiada'), ('kf', 'konferensia'), ('vs', 'vistavka')], max_length=3),
        ),
        migrations.AlterField(
            model_name='sotrudnikyionkafedra',
            name='degree',
            field=models.CharField(choices=[('dn', 'doktor nauk'), ('mg', 'magistr'), ('kn', 'kandidat nauk'), ('bk', 'bakalavr')], max_length=3),
        ),
        migrations.AlterField(
            model_name='sotrudnikyionkafedra',
            name='job',
            field=models.CharField(choices=[('as', 'asperan'), ('te', 'teacher')], max_length=3),
        ),
    ]
