# Generated by Django 4.2.7 on 2023-12-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_idparticipent_uchastnikyonnir_isparticipent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nir',
            name='type',
            field=models.CharField(choices=[('ol', 'olimpiada'), ('vs', 'vistavka'), ('kf', 'konferensia')], max_length=3),
        ),
        migrations.AlterField(
            model_name='sotrudnikyionkafedra',
            name='degree',
            field=models.CharField(choices=[('bk', 'bakalavr'), ('mg', 'magistr'), ('kn', 'kandidat nauk'), ('dn', 'doktor nauk')], max_length=3),
        ),
        migrations.AlterField(
            model_name='sotrudnikyionkafedra',
            name='job',
            field=models.CharField(choices=[('te', 'teacher'), ('as', 'asperan')], max_length=3),
        ),
    ]
