# Generated by Django 4.2.7 on 2023-12-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_sotrudnikyionkafedra_degree'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgkomitety',
            old_name='sotrudnikiOnKafedra',
            new_name='sotrudnik',
        ),
        migrations.AlterField(
            model_name='nir',
            name='type',
            field=models.CharField(choices=[('vs', 'vistavka'), ('kf', 'konferensia'), ('ol', 'olimpiada')], max_length=3),
        ),
        migrations.AlterField(
            model_name='sotrudnikyionkafedra',
            name='degree',
            field=models.CharField(choices=[('bk', 'bakalavr'), ('dn', 'doktor nauk'), ('kn', 'kandidat nauk'), ('mg', 'magistr')], max_length=3),
        ),
    ]
